import type { MobileLanguage } from "./settings-store";

export function mobileCopy(language: MobileLanguage) {
  const english = language === "en";
  return {
    remote: "Remote",
    settings: english ? "Settings" : "设置",
    back: english ? "Back" : "返回",
    appearance: english ? "Appearance" : "外观",
    appearanceDescription: english ? "Choose how Codex Remote looks on this device." : "选择 Codex Remote 在这台设备上的显示方式。",
    system: english ? "Follow system" : "跟随系统",
    light: english ? "Light" : "亮色",
    dark: english ? "Dark" : "暗色",
    language: english ? "Language" : "语言",
    languageDescription: english ? "Choose the language used by the mobile app." : "选择移动端界面使用的语言。",
    sendMode: english ? "New message delivery" : "新消息发送方式",
    sendModeDescription: english
      ? "Used when Codex is already working in a conversation."
      : "当 Codex 正在当前对话中工作时使用。",
    queue: english ? "Queue" : "排队",
    queueDescription: english ? "Queue until the current turn finishes" : "等待当前轮次完成后再发送",
    steer: english ? "Steer" : "引导",
    steerDescription: english ? "Send immediately into the current turn" : "立即插入当前轮次并调整执行方向",
    softwareUpdate: english ? "Software update" : "软件更新",
    softwareUpdateDescription: english ? "View the installed version and check for a newer release." : "查看当前安装版本并检测新版本。",
    currentVersion: english ? "Current version" : "当前版本",
    latestVersion: english ? "Latest version" : "最新版本",
    upToDate: english ? "You’re up to date" : "已是最新版本",
    scanAdd: english ? "Scan to add" : "扫码添加",
    newConnection: english ? "New connection" : "新建连接",
    devices: english ? "Devices" : "设备",
    chooseMac: english ? "Choose a Mac" : "选择一台 Mac",
    noConnections: english ? "No connections yet" : "还没有连接",
    noConnectionsDescription: english
      ? "Add the private network address and Codex Remote password for your Mac."
      : "添加 Mac 的本地私网地址和 Codex Remote 登录密码。",
    edit: english ? "Edit" : "修改",
    remove: english ? "Delete" : "删除",
    pairing: english ? "Pairing…" : "正在配对…",
    unavailable: english ? "Unavailable, scan again" : "连接不可用，请重新扫码",
    connectionChecking: english ? "Checking" : "检测中",
    connectionAvailable: english ? "Available" : "可用",
    connectionUnavailable: english ? "Unavailable" : "不可用",
    editConnection: english ? "Edit connection" : "修改连接",
    name: english ? "Name" : "名称",
    remoteAddress: english ? "Remote address" : "Remote 地址",
    password: english ? "Login password" : "登录密码",
    keepPassword: english ? "Leave blank to keep the current password" : "留空则保持原密码",
    enterPassword: english ? "Enter the Web login password" : "输入 Web 登录密码",
    cancel: english ? "Cancel" : "取消",
    validating: english ? "Validating…" : "验证中…",
    saveConnect: english ? "Save and connect" : "保存并连接",
    checkUpdate: english ? "Check for updates" : "检查更新",
    checking: english ? "Checking…" : "检查中…",
    retryUpdate: english ? "Retry update" : "重试更新",
    downloadVersion: (version: string) => english ? `Download ${version}` : `下载 ${version}`,
    updateConfirmation: (version: string) => english
      ? `Version ${version} is available. Download and update now?`
      : `发现新版本 ${version}，是否下载并更新？`,
    downloadingVersion: (version: string) => english ? `Downloading ${version}` : `正在下载 ${version}`,
    preparingInstall: english ? "Preparing install…" : "准备安装…",
    connectionActions: english ? "Connection actions" : "连接操作",
    deleteConfirmation: (name: string) => english ? `Delete “${name}”?` : `删除连接“${name}”？`,
    loginIncorrect: english ? "The login password is incorrect" : "登录密码不正确",
    addressUnavailable: english ? "This Remote address is unreachable" : "无法访问这个 Remote 地址",
    insecureAddress: english ? "HTTP is only allowed for local, VPN IP, or .local addresses" : "HTTP 只允许本地、VPN IP 或 .local 地址",
    passwordRequired: english ? "Enter the login password" : "请输入登录密码",
    pairingRequired: english ? "This connection is not paired. Scan it again." : "连接尚未配对，请重新扫码",
    pairingFailed: english ? "The QR code expired or pairing failed. Generate a new code on the Mac." : "二维码已失效或无法完成配对，请在 Mac 上重新生成",
    invalidAddress: english ? "The Remote address is invalid" : "Remote 地址格式不正确",
    checkFailed: english ? "Update check failed. Try again later." : "检查失败，请稍后重试",
    openDownloadFailed: english ? "Unable to open the download page" : "无法打开下载页面",
    downloadFailed: english ? "Download failed. Try again." : "下载失败，请重试",
  };
}
